# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cassavamax

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cassavamax.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4b31027b3beb4534821a1ae5a13aa68f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_28f4347210f34ef0829497d83c4084f4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cassavamax.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4b31027b3beb4534821a1ae5a13aa68f }}/app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cassavamax'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_829100d546bb4fb4bbb2270b3a6af3fa }}
        images: 'cassavamax.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4b31027b3beb4534821a1ae5a13aa68f }}/app:${{ github.sha }}'